# Generated by Django 4.2.4 on 2023-08-10 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
    ]
